<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="LAPTOP-HFVN6AVE" failures="2" tests="2" name="Default test(failed)" time="0.03" errors="0" timestamp="2023-04-19T12:17:04 IST">
  <testcase classname="testNg.FailedTestCase" name="t3" time="0.006">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.FailedTestCase.t3(FailedTestCase.java:24)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t3 -->
  <testcase classname="testNg.FailedTestCase" name="t1" time="0.0">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at testNg.FailedTestCase.t1(FailedTestCase.java:12)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- t1 -->
  <testcase classname="testNg.FailedTestCase" name="t2" time="0.0">
    <ignored/>
  </testcase> <!-- t2 -->
</testsuite> <!-- Default test(failed) -->
